services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./init-files/youtube.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: mypass
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb

  nodeapp:
    container_name: youtubeapiappcontainer
    build: .
    image: youtubeapipp:v1
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'mypass'
      DB_NAME: mydb
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: youtubeapiapp
      SERVER_PORT: 3000
    depends_on:
      - mysqldb
